### ISSUE TITLE
Latest image pulled but still old Jackett version

### ISSUE THREAD

**Issue by sorcierwax** [DyonR/docker-Jackettvpn#32]
Hello,

I don't understand what is happening. I've setup a watchtower to auto update my docker container with the latest images.
It pulls several time the latest JacketVPN image but Jacket is still version 0.16.1020.0.

dyonr/jackettvpn               latest              5315ca1bcf7d        3 hours ago         276MB

I've also tried to recreate the container and pulling the latest image before : same, version 0.16.1020.0

What am I doing wrong ?

Thx?

**Comment by DyonR** [comment]
You are correct indeed.  
I made an error on my Docker page by enabling build caching, because of that Docker kept using the old images that were cached.  
I disabled build caching (which I should've disabled in the beginning, my bad) and build a new image so it will be the actual latest version now. If you update the container again it will be the latest version of Jackett (v0.16.1138)

**Comment by sorcierwax** [comment]
Perfect, it works, thanks a lot !
